Models/Car.cs
namespace AutoShowroom.Models;

public class Car
{
    public int Id { get; set; }
    public string Brand { get; set; }
    public decimal Price { get; set; }
    public DateTime AssemblyDate { get; set; }
    public DateTime ImportDate { get; set; }
    public string Manufacturer { get; set; }
    public string CountryOfOrigin { get; set; }
}

Models/ErrorViewModel.cs
namespace AutoShowroom.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CarsController.cs
using AutoShowroom.Models;
using Microsoft.AspNetCore.Mvc;

namespace AutoShowroom.Controllers
{
    public class CarsController : Controller
    {
        private static List<Car> _cars = new List<Car>
        {
            new Car
            {
                Id = 1, Brand = "Toyota", Price = 25000, AssemblyDate = new DateTime(2020, 5, 1),
                ImportDate = new DateTime(2020, 6, 1), Manufacturer = "Toyota", CountryOfOrigin = "Japan"
            },
            new Car
            {
                Id = 2, Brand = "Ford", Price = 30000, AssemblyDate = new DateTime(2019, 8, 10),
                ImportDate = new DateTime(2019, 9, 1), Manufacturer = "Ford", CountryOfOrigin = "USA"
            },
            new Car
            {
                Id = 3, Brand = "BMW", Price = 45000, AssemblyDate = new DateTime(2021, 2, 15),
                ImportDate = new DateTime(2021, 3, 1), Manufacturer = "BMW", CountryOfOrigin = "Germany"
            },
            new Car
            {
                Id = 4, Brand = "Audi", Price = 50000, AssemblyDate = new DateTime(2022, 5, 12),
                ImportDate = new DateTime(2022, 6, 1), Manufacturer = "Audi", CountryOfOrigin = "Germany"
            },
            new Car
            {
                Id = 5, Brand = "Tesla", Price = 60000, AssemblyDate = new DateTime(2021, 1, 1),
                ImportDate = new DateTime(2021, 2, 1), Manufacturer = "Tesla", CountryOfOrigin = "USA"
            },
            new Car
            {
                Id = 6, Brand = "Mercedes", Price = 70000, AssemblyDate = new DateTime(2022, 10, 20),
                ImportDate = new DateTime(2022, 11, 1), Manufacturer = "Mercedes", CountryOfOrigin = "Germany"
            },
            new Car
            {
                Id = 7, Brand = "Honda", Price = 20000, AssemblyDate = new DateTime(2018, 7, 15),
                ImportDate = new DateTime(2018, 8, 1), Manufacturer = "Honda", CountryOfOrigin = "Japan"
            }
        };

        public IActionResult Index()
        {
            return View(_cars);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Car car)
        {
            if (!ModelState.IsValid)
            {
                return View(car);
            }

            car.Id = _cars.Max(c => c.Id) + 1;
            _cars.Add(car);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var car = _cars.FirstOrDefault(c => c.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        [HttpPost]
        public IActionResult Edit(Car car)
        {
            if (!ModelState.IsValid)
            {
                return View(car);
            }

            var existingCar = _cars.FirstOrDefault(c => c.Id == car.Id);
            if (existingCar == null)
            {
                return NotFound();
            }

            existingCar.Brand = car.Brand;
            existingCar.Price = car.Price;
            existingCar.AssemblyDate = car.AssemblyDate;
            existingCar.ImportDate = car.ImportDate;
            existingCar.Manufacturer = car.Manufacturer;
            existingCar.CountryOfOrigin = car.CountryOfOrigin;
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var car = _cars.FirstOrDefault(c => c.Id == id);
            
            if (car != null)
            {
                _cars.Remove(car);
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AutoShowroom.Models;

namespace AutoShowroom.Controllers;

public class HomeController(ILogger<HomeController> logger) : Controller
{
    private readonly ILogger<HomeController> _logger = logger;

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Cars/Create.cshtml
@model AutoShowroom.Models.Car

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssemblyDate" class="control-label"></label>
                <input asp-for="AssemblyDate" class="form-control" />
                <span asp-validation-for="AssemblyDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImportDate" class="control-label"></label>
                <input asp-for="ImportDate" class="form-control" />
                <span asp-validation-for="ImportDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Manufacturer" class="control-label"></label>
                <input asp-for="Manufacturer" class="form-control" />
                <span asp-validation-for="Manufacturer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryOfOrigin" class="control-label"></label>
                <input asp-for="CountryOfOrigin" class="form-control" />
                <span asp-validation-for="CountryOfOrigin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Views/Cars/Delete.cshtml
@model AutoShowroom.Models.Car

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssemblyDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssemblyDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImportDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImportDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountryOfOrigin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountryOfOrigin)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Cars/Details.cshtml
@model AutoShowroom.Models.Car

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssemblyDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssemblyDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImportDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImportDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CountryOfOrigin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CountryOfOrigin)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Cars/Edit.cshtml
@model AutoShowroom.Models.Car

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssemblyDate" class="control-label"></label>
                <input asp-for="AssemblyDate" class="form-control" />
                <span asp-validation-for="AssemblyDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImportDate" class="control-label"></label>
                <input asp-for="ImportDate" class="form-control" />
                <span asp-validation-for="ImportDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Manufacturer" class="control-label"></label>
                <input asp-for="Manufacturer" class="form-control" />
                <span asp-validation-for="Manufacturer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryOfOrigin" class="control-label"></label>
                <input asp-for="CountryOfOrigin" class="form-control" />
                <span asp-validation-for="CountryOfOrigin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Views/Cars/Index.cshtml
@model IEnumerable<AutoShowroom.Models.Car>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssemblyDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImportDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manufacturer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CountryOfOrigin)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssemblyDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImportDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manufacturer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CountryOfOrigin)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To The Car ShowRoom App</h1>
    <p>Made by Grosu Nicolae</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Grosu Nicolae | AutoShowroom | @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/AutoShowroom.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoShowroom</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - AutoShowroom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>